const fs = require("fs");
require("dotenv").config();
const express = require("express");
const mongoose = require("mongoose");
const { spawn } = require("child_process");
const path = require("path");
const Intelligence = require("./intelligence.models");

const app = express();
const PORT = 3000;
const MONGO_URI = process.env.MONGO_URI || "mongodb://localhost:27017/competitor_intelligence";

mongoose
  .connect(MONGO_URI)
  .then(() => console.log("MongoDB connected"))
  .catch((err) => {
    console.error("MongoDB connection error:", err.message);
    process.exit(1);
  });

app.use(express.json());

app.get("/api/scan", (req, res) => {
  const pythonBin = path.join(__dirname, ".venv", "bin", "python3");
  const pythonProcess = spawn(pythonBin, [path.join(__dirname, "swarm.py")], {
    env: { ...process.env },
  });

  let stdout = "";
  let stderr = "";

  pythonProcess.stdout.on("data", (data) => {
    stdout += data.toString();
  });

  pythonProcess.stderr.on("data", (data) => {
    stderr += data.toString();
  });

  pythonProcess.on("close", async (code) => {
    if (code !== 0) {
      return res.status(500).json({
        error: "Python swarm process failed",
        details: stderr,
        exitCode: code,
      });
    }

    try {
      const start = stdout.indexOf("{");
      const end = stdout.lastIndexOf("}") + 1;
      const jsonString = stdout.substring(start, end);
      const report = JSON.parse(jsonString);

      const intelligence = new Intelligence({
        date: new Date(),
        threats: report.threats || [],
        opportunities: report.opportunities || [],
        trends: report.trends || [],
      });

      const saved = await intelligence.save();

      // Generate Markdown file
      const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
      const fileName = `report_${timestamp}.md`;
      const mdContent = `# Competitor Intelligence Report
**Date:** ${new Date().toLocaleString()}
**Report ID:** ${saved._id}

## 🚨 Threats
${report.threats.map(t => `### ${t.title}\n> ${t.rationale}`).join("\n\n") || "No threats identified."}

## 💡 Opportunities
${report.opportunities.map(o => `### ${o.title}\n> ${o.rationale}`).join("\n\n") || "No opportunities identified."}

## 📈 Trends
${report.trends.map(t => `### ${t.title}\n> ${t.rationale}`).join("\n\n") || "No trends identified."}

---
*Generated by Competitor Intelligence Swarm*
`;

      fs.writeFileSync(path.join(__dirname, fileName), mdContent);
      console.log(`Markdown report generated: ${fileName}`);

      return res.status(200).json(saved);
    } catch (parseErr) {
      return res.status(500).json({
        error: "Failed to parse Python output",
        rawOutput: stdout,
        details: parseErr.message,
      });
    }
  });

  pythonProcess.on("error", (err) => {
    return res.status(500).json({
      error: "Failed to spawn Python process",
      details: err.message,
    });
  });
});

app.get("/api/reports", async (req, res) => {
  try {
    const reports = await Intelligence.find().sort({ date: -1 });
    return res.status(200).json(reports);
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

app.get("/api/reports/:id", async (req, res) => {
  try {
    const report = await Intelligence.findById(req.params.id);
    if (!report) {
      return res.status(404).json({ error: "Report not found" });
    }
    return res.status(200).json(report);
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
});

app.listen(PORT, () => {
  console.log(`Competitor Intelligence API running on http://localhost:${PORT}`);
});
